markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments:
  qa:
    - docs/development/git-strategy.md
    - docs/development/codebase-organization.md
    - docs/architecture/performance-targets.md
  architect:
    - docs/development/codebase-organization.md
    - docs/architecture/tech-stack.md
    - docs/architecture/system-design.md
  pm:
    - docs/development/git-strategy.md
    - docs/prd/epic-list.md
devLoadAlwaysFiles:
  # Epic 1 Focus - Only load what's relevant now
  - docs/architecture/coding-standards.md
  - docs/prd/epic-1-foundation-core-data-pipeline.md
  - docs/development/progressive-development-audit.md
  - docs/development/git-strategy.md
  - CLAUDE.md
  # Deferred until needed:
  # - docs/architecture/tech-stack.md  # Has Python/React info
  # - docs/architecture/source-tree.md  # Shows future structure
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
